definitions:
  dtos.EmailLoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dtos.EmailRegisterRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dtos.EmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  dtos.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dtos.UserResponse'
    type: object
  dtos.PhoneLoginRequest:
    properties:
      password:
        maxLength: 32
        minLength: 8
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - password
    - phone
    type: object
  dtos.PhoneRegisterRequest:
    properties:
      password:
        maxLength: 32
        minLength: 8
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - password
    - phone
    type: object
  dtos.PhoneRequest:
    properties:
      phone:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - phone
    type: object
  dtos.UpdateUserRequest:
    properties:
      bankAccountHolder:
        maxLength: 32
        minLength: 4
        type: string
      bankAccountName:
        maxLength: 32
        minLength: 4
        type: string
      bankAccountNumber:
        maxLength: 32
        minLength: 4
        type: string
      fileId:
        type: string
    required:
    - bankAccountHolder
    - bankAccountName
    - bankAccountNumber
    - fileId
    type: object
  dtos.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for a tutup lapak application.
  title: TutupLapak API
  version: "1.0"
paths:
  /v1/file:
    post:
      consumes:
      - multipart/form-data
      description: Upload user file
      parameters:
      - description: User File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Upload user file
      tags:
      - Upload File
  /v1/login/email:
    post:
      consumes:
      - application/json
      description: Login user with email and password
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.EmailLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Login with email
      tags:
      - auth
  /v1/login/phone:
    post:
      consumes:
      - application/json
      description: Login user with phone and password
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.PhoneLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Login with phone
      tags:
      - auth
  /v1/register/email:
    post:
      consumes:
      - application/json
      description: Register new user with email
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.EmailRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register with email
      tags:
      - auth
  /v1/register/phone:
    post:
      consumes:
      - application/json
      description: Register new user with phone
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.PhoneRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register with phone
      tags:
      - auth
  /v1/user:
    get:
      consumes:
      - application/json
      description: Get authenticated user's profile information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get current user profile
      tags:
      - Profile
      - protected
    put:
      consumes:
      - application/json
      description: Update an existing profile (partial updates allowed)
      parameters:
      - description: User update request (partial fields allowed)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update a profile
      tags:
      - Profile
  /v1/user/link/email:
    post:
      consumes:
      - application/json
      description: Update an existing email (partial updates allowed)
      parameters:
      - description: User update request (partial fields allowed)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.EmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update a email
      tags:
      - Profile
  /v1/user/link/phone:
    post:
      consumes:
      - application/json
      description: Update an existing phoe (partial updates allowed)
      parameters:
      - description: User update request (partial fields allowed)
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.PhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update a phone
      tags:
      - Profile
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
