apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
stringData:
  JWT_SECRET: {{ .Values.global.secrets.jwtSecret | quote }}
  INTERNAL_SECRET: {{ .Values.global.secrets.internalSecret | quote }}
---
{{- if and (not .Values.global.database.existingSecret.name) (not .Values.global.database.hardcode.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.global.namespace }}
stringData:
  DATABASE_URL: {{ .Values.global.database.url | quote }}
{{- end }}
