services:
  backend-infra:
    replicaCount: 1
    image:
      repository: us-west1-docker.pkg.dev/projectsprint-000001/ps-docker-repo/gojo/backend-infra
      tag: d0d9f7f
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3000
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    env:
      DATABASE_URL: "postgresql://usrprd:pswdprd@gojo-postgres-postgresql:5432/db-tutup-lapak-prd?sslmode=disable"
      DATABASE_HOST: gojo-postgres-postgresql
      DATABASE_PORT: "5432"
      DATABASE_NAME: db-tutup-lapak-prd
      DATABASE_USER: usrprd
      DATABASE_PASSWORD: pswdprd
      REDIS_HOST: gojo-redis-master
      REDIS_PORT: "6379"
      SERVER_PORT: 3000

  auth-service:
    replicaCount: 1
    image:
      repository: us-west1-docker.pkg.dev/projectsprint-000001/ps-docker-repo/gojo/auth-service
      tag: d0d9f7f
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3001
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    env:
      DATABASE_URL: "postgresql://usrprd:pswdprd@gojo-postgres-postgresql:5432/db-tutup-lapak-prd?sslmode=disable"
      DATABASE_HOST: gojo-postgres-postgresql
      DATABASE_PORT: "5432"
      DATABASE_NAME: db-tutup-lapak-prd
      DATABASE_USER: usrprd
      DATABASE_PASSWORD: pswdprd
      REDIS_HOST: gojo-redis-master
      REDIS_PORT: "6379"
      SERVER_PORT: 3001
      JWT_SECRET: nv6FNtvAmBmUMHRSta8aSZNwiw4XAH

  profile-service:
    replicaCount: 1
    image:
      repository: us-west1-docker.pkg.dev/projectsprint-000001/ps-docker-repo/gojo/profile-service
      tag: d0d9f7f
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3002
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    env:
      DATABASE_URL: "postgresql://usrprd:pswdprd@gojo-postgres-postgresql:5432/db-tutup-lapak-prd?sslmode=disable"
      DATABASE_HOST: gojo-postgres-postgresql
      DATABASE_PORT: "5432"
      DATABASE_NAME: db-tutup-lapak-prd
      DATABASE_USER: usrprd
      DATABASE_PASSWORD: pswdprd
      REDIS_HOST: gojo-redis-master
      REDIS_PORT: "6379"
      SERVER_PORT: 3002
      JWT_SECRET: nv6FNtvAmBmUMHRSta8aSZNwiw4XAH

  product-service:
    replicaCount: 1
    image:
      repository: us-west1-docker.pkg.dev/projectsprint-000001/ps-docker-repo/gojo/product-service
      tag: d0d9f7f
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3003
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    env:
      DATABASE_URL: "postgresql://usrprd:pswdprd@gojo-postgres-postgresql:5432/db-tutup-lapak-prd?sslmode=disable"
      DATABASE_HOST: gojo-postgres-postgresql
      DATABASE_PORT: "5432"
      DATABASE_NAME: db-tutup-lapak-prd
      DATABASE_USER: usrprd
      DATABASE_PASSWORD: pswdprd
      REDIS_HOST: gojo-redis-master
      REDIS_PORT: "6379"
      SERVER_PORT: 3003
      JWT_SECRET: nv6FNtvAmBmUMHRSta8aSZNwiw4XAH

  purchase-service:
    replicaCount: 1
    image:
      repository: us-west1-docker.pkg.dev/projectsprint-000001/ps-docker-repo/gojo/purchase-service
      tag: d0d9f7f
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3004
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
    env:
      DATABASE_URL: "postgresql://usrprd:pswdprd@gojo-postgres-postgresql:5432/db-tutup-lapak-prd?sslmode=disable"
      DATABASE_HOST: gojo-postgres-postgresql
      DATABASE_PORT: "5432"
      DATABASE_NAME: db-tutup-lapak-prd
      DATABASE_USER: usrprd
      DATABASE_PASSWORD: pswdprd
      REDIS_HOST: gojo-redis-master
      REDIS_PORT: "6379"
      SERVER_PORT: 3004
      JWT_SECRET: nv6FNtvAmBmUMHRSta8aSZNwiw4XAH
      PRODUCT_SERVICE_URL: http://product-service:3003
      USER_SERVICE_URL: http://profile-service:3002